name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Télécharger le projet
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Installer dépendances système
        run: |
          sudo apt update
          sudo apt install -y \
          git zip unzip openjdk-17-jdk python3-pip \
          autoconf libtool pkg-config zlib1g-dev \
          libncurses5-dev libncursesw5-dev libtinfo5 \
          cmake libffi-dev libssl-dev

      - name: Installer Buildozer
        run: |
          pip install --upgrade pip
          pip install buildozer cython

      - name: Construire APK
        run: |
          buildozer android debug
